// packages/svelte/src/Select.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { Select as SelectElement } from "@unofficialbox/box-open-elements/select";

  SelectElement.register();

  type SelectOption = { label: string; value: string };
  type ValueChangedEvent = CustomEvent<{ value: string }>;
  type Props = {
    element?: SelectElement;
    label?: string;
    value?: string;
    options?: SelectOption[];
    disabled?: boolean;
    name?: string;
    invalid?: boolean;
    errorMessage?: string;
    onValueChanged?: (event: ValueChangedEvent) => void;
    children?: Snippet;
    [key: string]: unknown;
  };

  let {
    element = $bindable(),
    label,
    value,
    options,
    disabled = false,
    name,
    invalid = false,
    errorMessage,
    onValueChanged,
    children,
    ...rest
  }: Props = $props();

  $effect(() => {
    if (!element || !onValueChanged) return;
    const listener = onValueChanged as EventListener;
    element.addEventListener("value-changed", listener);
    return () => element?.removeEventListener("value-changed", listener);
  });
</script>

<box-select
  bind:this={element}
  {...rest}
  {label}
  {value}
  {options}
  {disabled}
  {name}
  {invalid}
  {errorMessage}
>
  {@render children?.()}
</box-select>

// packages/angular/src/select.ts
import {
  Directive,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  Output,
} from "@angular/core";
import { Select as SelectElement } from "@unofficialbox/box-open-elements/select";
import type { ValueChangedDetail } from "./text-field.js";

SelectElement.register();

export type SelectOption = { label: string; value: string };
export type SelectValueChangedEvent = CustomEvent<ValueChangedDetail>;

/** Typed standalone Angular directive for `<box-select>`. */
@Directive({ selector: "box-select", standalone: true })
export class Select implements OnDestroy {
  readonly element: SelectElement;
  private readonly valueChangedListener = (event: Event): void => {
    this.valueChanged.emit(event as SelectValueChangedEvent);
  };

  @Output("value-changed") readonly valueChanged =
    new EventEmitter<SelectValueChangedEvent>();

  constructor(host: ElementRef<SelectElement>) {
    this.element = host.nativeElement;
    this.element.addEventListener("value-changed", this.valueChangedListener);
  }

  @Input() set label(value: string | undefined) {
    if (value !== undefined) this.element.label = value;
  }

  @Input() set value(value: string | undefined) {
    if (value !== undefined) this.element.value = value;
  }

  @Input() set options(value: SelectOption[] | undefined) {
    if (value !== undefined) this.element.options = value;
  }

  @Input() set name(value: string | undefined) {
    if (value !== undefined) this.element.name = value;
  }

  @Input() set errorMessage(value: string | undefined) {
    if (value !== undefined) this.element.errorMessage = value;
  }

  @Input() set disabled(value: boolean | undefined) {
    this.element.disabled = Boolean(value);
  }

  @Input() set invalid(value: boolean | undefined) {
    this.element.invalid = Boolean(value);
  }

  ngOnDestroy(): void {
    this.element.removeEventListener("value-changed", this.valueChangedListener);
  }
}
