// packages/angular/src/dialog.ts
import {
  Directive,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  Output,
} from "@angular/core";
import { Dialog as DialogElement } from "@unofficialbox/box-open-elements/dialog";

DialogElement.register();

export type DialogConfirmTone = "primary" | "danger";
export type DialogSize = "small" | "medium" | "large" | "fullscreen";
export type OpenChangedEvent = CustomEvent<{ open: boolean }>;

/** Typed standalone Angular directive for the controlled `<box-dialog>`. */
@Directive({ selector: "box-dialog", standalone: true })
export class Dialog implements OnDestroy {
  readonly element: DialogElement;
  private readonly openChangedListener = (event: Event): void => {
    this.openChanged.emit(event as OpenChangedEvent);
  };
  private readonly confirmListener = (event: Event): void => {
    this.confirm.emit(event as CustomEvent<null>);
  };
  private readonly cancelListener = (event: Event): void => {
    this.cancel.emit(event as CustomEvent<null>);
  };

  @Output("open-changed") readonly openChanged =
    new EventEmitter<OpenChangedEvent>();
  @Output() readonly confirm = new EventEmitter<CustomEvent<null>>();
  @Output() readonly cancel = new EventEmitter<CustomEvent<null>>();

  constructor(host: ElementRef<DialogElement>) {
    this.element = host.nativeElement;
    this.element.addEventListener("open-changed", this.openChangedListener);
    this.element.addEventListener("confirm", this.confirmListener);
    this.element.addEventListener("cancel", this.cancelListener);
  }

  @Input() set open(value: boolean | undefined) {
    this.element.open = Boolean(value);
  }

  @Input() set heading(value: string | undefined) {
    if (value !== undefined) this.element.heading = value;
  }

  @Input() set description(value: string | undefined) {
    if (value !== undefined) this.element.description = value;
  }

  @Input() set confirmLabel(value: string | undefined) {
    if (value !== undefined) this.element.confirmLabel = value;
  }

  @Input() set confirmTone(value: DialogConfirmTone | undefined) {
    if (value !== undefined) this.element.confirmTone = value;
  }

  @Input() set size(value: DialogSize | undefined) {
    if (value !== undefined) this.element.size = value;
  }

  ngOnDestroy(): void {
    this.element.removeEventListener("open-changed", this.openChangedListener);
    this.element.removeEventListener("confirm", this.confirmListener);
    this.element.removeEventListener("cancel", this.cancelListener);
  }
}

// packages/svelte/src/Dialog.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { Dialog as DialogElement } from "@unofficialbox/box-open-elements/dialog";

  DialogElement.register();

  type DialogSize = "small" | "medium" | "large" | "fullscreen";
  type Props = {
    element?: DialogElement;
    open?: boolean;
    heading?: string;
    description?: string;
    confirmLabel?: string;
    confirmTone?: "primary" | "danger";
    size?: DialogSize;
    onOpenChanged?: (event: CustomEvent<{ open: boolean }>) => void;
    onConfirm?: (event: CustomEvent<null>) => void;
    onCancel?: (event: CustomEvent<null>) => void;
    children?: Snippet;
    [key: string]: unknown;
  };

  let {
    element = $bindable(),
    open = false,
    heading,
    description,
    confirmLabel,
    confirmTone,
    size,
    onOpenChanged,
    onConfirm,
    onCancel,
    children,
    ...rest
  }: Props = $props();

  $effect(() => {
    if (!element) return;
    const bindings: Array<[string, EventListener | undefined]> = [
      ["open-changed", onOpenChanged as EventListener | undefined],
      ["confirm", onConfirm as EventListener | undefined],
      ["cancel", onCancel as EventListener | undefined],
    ];
    for (const [eventName, listener] of bindings) {
      if (listener) element.addEventListener(eventName, listener);
    }
    return () => {
      for (const [eventName, listener] of bindings) {
        if (listener) element?.removeEventListener(eventName, listener);
      }
    };
  });
</script>

<box-dialog
  bind:this={element}
  {...rest}
  {open}
  {heading}
  {description}
  {confirmLabel}
  {confirmTone}
  {size}
>
  {@render children?.()}
</box-dialog>
