// packages/angular/src/text-field.ts
import {
  Directive,
  ElementRef,
  EventEmitter,
  Input,
  OnDestroy,
  Output,
} from "@angular/core";
import { TextField as TextFieldElement } from "@unofficialbox/box-open-elements/text-field";

TextFieldElement.register();

export type ValueChangedDetail = { value: string };
export type ValueChangedEvent = CustomEvent<ValueChangedDetail>;

/** Typed standalone Angular directive for `<box-text-field>`. */
@Directive({ selector: "box-text-field", standalone: true })
export class TextField implements OnDestroy {
  readonly element: TextFieldElement;
  private readonly valueChangedListener = (event: Event): void => {
    this.valueChanged.emit(event as ValueChangedEvent);
  };

  @Output("value-changed") readonly valueChanged =
    new EventEmitter<ValueChangedEvent>();

  constructor(host: ElementRef<TextFieldElement>) {
    this.element = host.nativeElement;
    this.element.addEventListener("value-changed", this.valueChangedListener);
  }

  @Input() set label(value: string | undefined) {
    if (value !== undefined) this.element.label = value;
  }

  @Input() set value(value: string | undefined) {
    if (value !== undefined) this.element.value = value;
  }

  @Input() set placeholder(value: string | undefined) {
    if (value !== undefined) this.element.placeholder = value;
  }

  @Input() set name(value: string | undefined) {
    if (value !== undefined) this.element.name = value;
  }

  @Input() set errorMessage(value: string | undefined) {
    if (value !== undefined) this.element.errorMessage = value;
  }

  @Input() set disabled(value: boolean | undefined) {
    this.element.disabled = Boolean(value);
  }

  @Input() set invalid(value: boolean | undefined) {
    this.element.invalid = Boolean(value);
  }

  ngOnDestroy(): void {
    this.element.removeEventListener("value-changed", this.valueChangedListener);
  }
}

// packages/svelte/src/TextField.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { TextField as TextFieldElement } from "@unofficialbox/box-open-elements/text-field";

  TextFieldElement.register();

  type ValueChangedEvent = CustomEvent<{ value: string }>;
  type Props = {
    element?: TextFieldElement;
    label?: string;
    value?: string;
    placeholder?: string;
    disabled?: boolean;
    name?: string;
    invalid?: boolean;
    errorMessage?: string;
    onValueChanged?: (event: ValueChangedEvent) => void;
    children?: Snippet;
    [key: string]: unknown;
  };

  let {
    element = $bindable(),
    label,
    value,
    placeholder,
    disabled = false,
    name,
    invalid = false,
    errorMessage,
    onValueChanged,
    children,
    ...rest
  }: Props = $props();

  $effect(() => {
    if (!element || !onValueChanged) return;
    const listener = onValueChanged as EventListener;
    element.addEventListener("value-changed", listener);
    return () => element?.removeEventListener("value-changed", listener);
  });
</script>

<box-text-field
  bind:this={element}
  {...rest}
  {label}
  {value}
  {placeholder}
  {disabled}
  {name}
  {invalid}
  {errorMessage}
>
  {@render children?.()}
</box-text-field>
